### ISSUE TITLE
Log Analysis does not work well with large file

### ISSUE THREAD

**Issue by passionyeh** [SoySauceFor3/log-analysis#1]
Hi XinyaYang0506,

Log-analysis extension is a great addition to VS Code. However, I find it's not working well with large log file. When log file size with few hundred megabytes, it in general doesn't try to annotate the file and FocusMode simply doesn't work. Its response to small file is quick and stable. For large files, sometimes it does try to annotate but I don't really know the rule. Most of the time it simply refuse to work with large log file.

Have you noticed such a problem?

**Comment by SoySauceFor3** [comment]
hi! (sorry for such a late late response)
I actually have done some test myself when I first saw your issue (three years ago) and at that time I thought it is not fixable, so I did not say anything. 
I am not optimistic about if vscode have had provided any new features in their api about this in the past a few years, but who knows? 
Can you let me know if you still have this need? If so I might spend sometime looking into this.

**Comment by JeanTracker** [comment]
When opening files larger than 50MB, the extension is disabled due to VSCode performance policies. The extension will be activated if you use the following extension. For more detailed information, please refer to the extension documentation.
[Large file support for extensions](https://marketplace.visualstudio.com/items?itemName=mbehr1.vsc-lfs).
